"""empty message

Revision ID: 5549e8d18955
Revises: 
Create Date: 2019-04-03 18:57:56.054978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5549e8d18955'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_currency',
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('currency_name', sa.String(length=128), nullable=True),
    sa.Column('currency_status', sa.Integer(), nullable=True),
    sa.Column('currency_create_time', sa.DateTime(), nullable=True),
    sa.Column('currency_contract_address', sa.String(length=512), nullable=True),
    sa.Column('currency_update_time', sa.DateTime(), nullable=True),
    sa.Column('currency_withdraw_commission', sa.Float(), nullable=True),
    sa.Column('currency_extract_count_min', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('currency_id'),
    sa.UniqueConstraint('currency_id')
    )
    op.create_table('t_user',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('phone_status', sa.Integer(), nullable=True),
    sa.Column('user_status', sa.Integer(), nullable=True),
    sa.Column('user_password', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('t_user_balance',
    sa.Column('balance_id', sa.String(length=128), nullable=False),
    sa.Column('sa_user_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['sa_user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('balance_id')
    )
    op.create_index(op.f('ix_t_user_balance_balance_id'), 't_user_balance', ['balance_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_user_balance_balance_id'), table_name='t_user_balance')
    op.drop_table('t_user_balance')
    op.drop_table('t_user')
    op.drop_table('t_currency')
    # ### end Alembic commands ###
